"""enterprise_lifecycle_and_governance

Revision ID: e7322935d345
Revises: d5c3a4b4555c
Create Date: 2026-09-29 15:27:14.141346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7322935d345'
down_revision: Union[str, Sequence[str], None] = 'd5c3a4b4555c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_action_audits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interaction_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('action_name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('execution_mode', sa.String(), nullable=True),
    sa.Column('exceeds_confirmation_threshold', sa.Boolean(), nullable=True),
    sa.Column('threshold_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_action_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_action_audits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_action_audits_interaction_id'), ['interaction_id'], unique=False)

    op.create_table('approval_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('risk_category', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approver_1', sa.String(), nullable=True),
    sa.Column('approver_1_note', sa.Text(), nullable=True),
    sa.Column('approver_1_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approver_2', sa.String(), nullable=True),
    sa.Column('approver_2_note', sa.Text(), nullable=True),
    sa.Column('approver_2_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_status'), ['status'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=False),
    sa.Column('entry_hash', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('target_entity', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entry_hash'), ['entry_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_sequence_number'), ['sequence_number'], unique=True)

    op.create_table('contradiction_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('memory_id_a', sa.String(), nullable=False),
    sa.Column('memory_id_b', sa.String(), nullable=False),
    sa.Column('conflict_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('precedence_rule', sa.String(), nullable=True),
    sa.Column('auto_resolved', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contradiction_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contradiction_reviews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contradiction_reviews_memory_id_a'), ['memory_id_a'], unique=False)
        batch_op.create_index(batch_op.f('ix_contradiction_reviews_memory_id_b'), ['memory_id_b'], unique=False)
        batch_op.create_index(batch_op.f('ix_contradiction_reviews_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('subscribed_events', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_subscriptions_id'), ['id'], unique=False)

    op.create_table('memory_transitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('from_state', sa.String(), nullable=False),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_references.memory_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_transitions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_transitions_memory_id'), ['memory_id'], unique=False)

    op.create_table('memory_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_references.memory_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_versions_id'), ['id'], unique=False)
        batch_op.create_index('ix_memory_versions_lookup', ['memory_id', 'version_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_versions_memory_id'), ['memory_id'], unique=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(), server_default=sa.text("'General'"), nullable=False))
        batch_op.add_column(sa.Column('system_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tools', sa.JSON(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corrector_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sanitized_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_quarantined', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('quarantine_reason', sa.String(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(), server_default=sa.text("'default'"), nullable=False))
        batch_op.add_column(sa.Column('rejected_memory_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('execution_trace', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tool_calls', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('reasoning_mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cost_usd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tokens_used', sa.Integer(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_interactions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('lesson_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specific_rule', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('generalized_rule', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_negative_guardrail', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('suggested_conditions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('requires_two_person_approval', sa.Boolean(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_lesson_candidates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_candidates_interaction_id'), ['interaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_candidates_is_promoted'), ['is_promoted'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_candidates_is_validated'), ['is_validated'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_candidates_promoted_memory_id'), ['promoted_memory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_candidates_risk_level'), ['risk_level'], unique=False)

    with op.batch_alter_table('memory_references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(), server_default=sa.text("'active'"), nullable=False))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('parent_memory_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('root_memory_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.String(), server_default=sa.text("'default'"), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('customer_segments', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('conditions', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_negative_guardrail', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('confidence_breakdown', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('verifier_role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('review_due_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_stale', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('merged_source_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('dedup_cluster_id', sa.String(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_memory_references_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_references_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_references_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_references_is_negative_guardrail'), ['is_negative_guardrail'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_references_is_stale'), ['is_stale'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_references_parent_memory_id'), ['parent_memory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_references_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_references_root_memory_id'), ['root_memory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_references_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_references_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_memory_tenant_state', ['tenant_id', 'state'], unique=False)

    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_outcomes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcomes_interaction_id'), ['interaction_id'], unique=False)

    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_system_events_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_memory_id'), ['memory_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_events_memory_id'))
        batch_op.drop_index(batch_op.f('ix_system_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_system_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_system_events_agent_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_interaction_id'))
        batch_op.drop_index(batch_op.f('ix_outcomes_created_at'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('memory_references', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_tenant_state')
        batch_op.drop_index(batch_op.f('ix_memory_references_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_memory_references_state'))
        batch_op.drop_index(batch_op.f('ix_memory_references_root_memory_id'))
        batch_op.drop_index(batch_op.f('ix_memory_references_priority'))
        batch_op.drop_index(batch_op.f('ix_memory_references_parent_memory_id'))
        batch_op.drop_index(batch_op.f('ix_memory_references_is_stale'))
        batch_op.drop_index(batch_op.f('ix_memory_references_is_negative_guardrail'))
        batch_op.drop_index(batch_op.f('ix_memory_references_department'))
        batch_op.drop_index(batch_op.f('ix_memory_references_created_at'))
        batch_op.drop_index(batch_op.f('ix_memory_references_candidate_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('dedup_cluster_id')
        batch_op.drop_column('merged_source_ids')
        batch_op.drop_column('is_stale')
        batch_op.drop_column('review_due_at')
        batch_op.drop_column('valid_until')
        batch_op.drop_column('valid_from')
        batch_op.drop_column('verifier_role')
        batch_op.drop_column('confidence_breakdown')
        batch_op.drop_column('is_negative_guardrail')
        batch_op.drop_column('priority')
        batch_op.drop_column('conditions')
        batch_op.drop_column('customer_segments')
        batch_op.drop_column('department')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('root_memory_id')
        batch_op.drop_column('parent_memory_id')
        batch_op.drop_column('version')
        batch_op.drop_column('state')

    with op.batch_alter_table('lesson_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_candidates_risk_level'))
        batch_op.drop_index(batch_op.f('ix_lesson_candidates_promoted_memory_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_candidates_is_validated'))
        batch_op.drop_index(batch_op.f('ix_lesson_candidates_is_promoted'))
        batch_op.drop_index(batch_op.f('ix_lesson_candidates_interaction_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_candidates_created_at'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('requires_two_person_approval')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('suggested_conditions')
        batch_op.drop_column('is_negative_guardrail')
        batch_op.drop_column('generalized_rule')
        batch_op.drop_column('specific_rule')

    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_task_type'))
        batch_op.drop_index(batch_op.f('ix_interactions_status'))
        batch_op.drop_index(batch_op.f('ix_interactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_interactions_agent_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('tokens_used')
        batch_op.drop_column('cost_usd')
        batch_op.drop_column('reasoning_mode')
        batch_op.drop_column('tool_calls')
        batch_op.drop_column('execution_trace')
        batch_op.drop_column('rejected_memory_ids')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('quarantine_reason')
        batch_op.drop_column('is_quarantined')
        batch_op.drop_column('sanitized_text')
        batch_op.drop_column('corrector_id')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('tools')
        batch_op.drop_column('system_prompt')
        batch_op.drop_column('department')

    with op.batch_alter_table('memory_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_versions_memory_id'))
        batch_op.drop_index('ix_memory_versions_lookup')
        batch_op.drop_index(batch_op.f('ix_memory_versions_id'))

    op.drop_table('memory_versions')
    with op.batch_alter_table('memory_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_transitions_memory_id'))
        batch_op.drop_index(batch_op.f('ix_memory_transitions_id'))

    op.drop_table('memory_transitions')
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_subscriptions_id'))

    op.drop_table('webhook_subscriptions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('contradiction_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contradiction_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_contradiction_reviews_memory_id_b'))
        batch_op.drop_index(batch_op.f('ix_contradiction_reviews_memory_id_a'))
        batch_op.drop_index(batch_op.f('ix_contradiction_reviews_id'))

    op.drop_table('contradiction_reviews')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_sequence_number'))
        batch_op.drop_index(batch_op.f('ix_audit_log_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entry_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_candidate_id'))

    op.drop_table('approval_requests')
    with op.batch_alter_table('agent_action_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_action_audits_interaction_id'))
        batch_op.drop_index(batch_op.f('ix_agent_action_audits_id'))

    op.drop_table('agent_action_audits')
    # ### end Alembic commands ###
